### ISSUE TITLE
Add support for embeddable translations

### ISSUE THREAD

**Issue by ellmetha** [crystal-i18n/i18n#4]
# Description

Right now `crystal-i18n` requires raw translations to be available on the file system where compiled binaries are deployed in order to allow translation lookups. While this works fine for a number of use cases, a common need is to be able to embed the raw translations _inside_ compiled binaries.

In order to support this, we could allow translation loaders to define an optional `embed` macro that would be used to initialize loaders whose translations are embedded in the final binary:

```crystal
I18n.config.loaders << I18n::Loader::YAML.embed("config/locales")
```

**Comment by straight-shoota** [comment]
A simple emebed macro would already go a great way to enable self-contained applications.

As an idea for further enhancements I'd like to point to crinja's loader system: https://github.com/straight-shoota/crinja/blob/15c267c5280bcb78a1f3f472ac5cb3843176fdd1/src/loader.cr
It serves a similar purpose for loading templates at runtime, either from the file system or baked in. It's also extensible to allow additional sources (for example a database). There's also a component for overrides / fallback behaviour: [`ChoiceLoader`](https://straight-shoota.github.io/crinja/api/latest/Crinja/Loader/ChoiceLoader.html). The exact usage requirements are a bit different because templates can be dynamically loaded at any point, whereas translations a probably loaded only once during the runtime of a program. But I could still see value in a hierarchial system, which essentially allows fallbacks for translation terms. For example the base translations for an app would be baked in, but they can be selectively overriden by translations in the local file system, or a database.

**Comment by ellmetha** [comment]
Thanks for your suggestion! 😃 

I will have a look at it. Right now it's possible to configure multiple translations loaders and they are all used to initialize a single catalog of translations by default (the one used when doing lookups with the top-level `I18n.t`): this means that the order of loaders is important because the latest loaders can in theory "override" the translations that were defined by previous loaders. This "override" behavior only applies for a given locale of course ; [fallbacks between locales](https://crystal-i18n.github.io/configuration.html#fallbacks) are handled a bit differently through a dedicated configuration option.

**Comment by mamantoha** [comment]
Thanks @ellmetha 🙏🏻
